# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='gateway_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
