version: '3'

volumes:
  static:

services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:8001"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - web
  web:
    command: ["./wait-for.sh", "db:5432", "--", "gunicorn", "soundproud.wsgi", "-b", "0.0.0.0:8000"]
    ports:
      - "8000"
    volumes:
      - static:/static
    environment:
      PROD: 1
