from . import env

CELERY_BROKER_URL = 'amqp://broker'
DOMAIN = env.DOMAIN
PROTOCOL = env.PROTOCOL
SOUNDCLOUD_CLIENT_ID = env.SOUNDCLOUD_CLIENT_ID
SOUNDCLOUD_CLIENT_SECRET = env.SOUNDCLOUD_CLIENT_SECRET
SOUNDCLOUD_USERNAME = env.SOUNDCLOUD_USERNAME
SOUNDCLOUD_PASSWORD = env.SOUNDCLOUD_PASSWORD
