# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_track_gateway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
