# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20170726_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artwork_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
